
language: java

env:
  global:
    - TMPDIR=/tmp

jdk:
  - oraclejdk8
  - oraclejdk7

before_install:
   - pwd
   - export LD_LIBRARY_PATH=$(pwd)/jayhorn/native_lib

script:   
   - gradle check

after_success:
   - gradle jacocoRootReport coveralls

deply:
   - deploy_results.sh &2>/dev/null
   
notifications:
  slack: jayhorn:gYFX9JnLgy7CxzjuV1K3OoJG
