
language: java

jdk:
  - oraclejdk8
  - oraclejdk7

before_install:
   - "export LD_LIBRARY_PATH=jayhorn/jayhorn/native_lib:$LD_LIBRARY_PATH"

script:
   - gradle check

after_success:
   - gradle jacocoRootReport coveralls
